### ISSUE TITLE
service discovery

### ISSUE THREAD

**Issue by vielmetti** [warpnet/awesome-prometheus#14]
Any interest in adding a "service discovery" section?  There should be a whole set of these out there.

Some examples for reference

* https://github.com/packethost/prometheus-packet-sd
* https://github.com/scaleway/prometheus-scw-sd
* https://github.com/totvslabs/prometheus-digitalocean-sd

**Comment by roaldnefs** [comment]
Thanks for the suggestion! I am open to new sections, I think more people will benefit from this. Would you like to submit a first draft?

**Comment by roaldnefs** [comment]
@vielmetti, I will close this PR. Feel free to send in a pull request for the new section and refer back to this issue!
