### ISSUE TITLE
High Availability - Cortex, Thanos

### ISSUE THREAD

**Issue by jorisroovers** [warpnet/awesome-prometheus#15]
I just discovered these 2 Prometheus High Availability projects:

https://github.com/cortexproject/cortex
https://github.com/thanos-io/thanos

Would you be interested in adding these under a High Availability section? If so, I can open a PR :-)

Disclaimer: I haven't tried either of these projects, just think they are relevant for this list.

**Comment by roaldnefs** [comment]
Thanks @jorisroovers for your proposal! Feel free to create a PR to add both to a new section, don't forget to update the table of contents.
