### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by paulfantom** [warpnet/awesome-prometheus#3]
We host our prometheus demo site which is provisioned every day using our ansible roles, here is link for repo containing ansible playbook: https://github.com/cloudalchemy/demo-site

Link to prometheus: https://github.com/cloudalchemy/demo-site

If you like it, I can make a PR, but I don't know in which section.

**Comment by roaldnefs** [comment]
Feel free to add it to the `uncategorized` section! Once we gather more demo's we could add a `demo` section.

Thanks in advance for your contribution! :unicorn:
